### ISSUE TITLE
paramiko.ssh_exception.SSHException: No authentication methods available

### ISSUE THREAD

**Issue by FlightZCB** [FederatedAI/FedVision#17]
When deploying in our local Linux environment， we use "fedvision-deploy deploy deploy --config standalone_template.yaml", but it occurs the error that "paramiko.ssh_exception.SSHException: No authentication methods available"

(In our /etc/ssh/ssh_config: PasswordAuthentication yes)

**Comment by sagewe** [comment]
> When deploying in our local Linux environment， we use "fedvision-deploy deploy deploy --config standalone_template.yaml", but it occurs the error that "paramiko.ssh_exception.SSHException: No authentication methods available"
> 
> (In our /etc/ssh/ssh_config: PasswordAuthentication yes)

according to [this issue](https://stackoverflow.com/questions/14326665/ssh-python-with-paramiko-issue): `You should provide either a password or a private key`. Since we don't provide `password appproch` in this version, `private key method` is needed.  
Try appends contents of ~/.ssh/id_rsa.pub to ~/.ssh/authorized_keys.

**Comment by FlightZCB** [comment]
Thank you. If I do like abovePermissionError: [Errno 13] Permission denied: '/home/zcb/.ssh/id_rsa'

**Comment by FlightZCB** [comment]
> > When deploying in our local Linux environment， we use "fedvision-deploy deploy deploy --config standalone_template.yaml", but it occurs the error that "paramiko.ssh_exception.SSHException: No authentication methods available"
> > (In our /etc/ssh/ssh_config: PasswordAuthentication yes)
> 
> according to [this issue](https://stackoverflow.com/questions/14326665/ssh-python-with-paramiko-issue): `You should provide either a password or a private key`. Since we don't provide `password appproch` in this version, `private key method` is needed.
> Try appends contents of ~/.ssh/id_rsa.pub to ~/.ssh/authorized_keys.

Thank you. If I do like above, it will raise "PermissionError: [Errno 13] Permission denied: '/home/zcb/.ssh/id_rsa'"
Then I try "sudo fedvision-deploy deploy deploy --config standalone_template.yaml", but it show that: "sudo: fedvision-deploy：找不到命令" after I enter my password

**Comment by imtiyazuddin** [comment]
any fix for this??
