### ISSUE TITLE
Error: trainer_0 failed, return code 134

### ISSUE THREAD

**Issue by dipmukherg** [FederatedAI/FedVision#18]
Getting this error always while running "sh FedVision/examples/paddle_detection/run.sh 127.0.0.1:10002" in standalone mode in linux. "fedvision.framework.utils.exception.FedvisionWorkerException: execute task: trainer_0 failed, return code: 134". Attaching the logs for reference. Any lead will e very much helpful.
[worker-127.0.0.1.log](https://github.com/FederatedAI/FedVision/files/6127671/worker-127.0.0.1.log)
[trainer.log](https://github.com/FederatedAI/FedVision/files/6127672/trainer.log)

**Comment by sagewe** [comment]
`return code: 134 means program was aborted`
maybe you could check stderr/stdout in logs/jobs/<jobid>/worker_0 for more imformation?
