### ISSUE TITLE
fedvision_deploy_toolkit/_deploy.py", line 69, in _maybe_create_python_venv     raise RuntimeError(f"python executable {machine['python']} not valid")

### ISSUE THREAD

**Issue by kevinsummer219** [FederatedAI/FedVision#19]
hi, 
  Can you help focus on the issue, i am follow the step, it will occur the error:
  python -m venv venv && source venv/bin/activate
  python -m pip install -U pip && python -m pip install fedvision_deploy_toolkit
  fedvision-deploy template standalone
  fedvision-deploy deploy deploy --config standalone_template.yaml

  error log:
  File "/home/yangyu/work/fed_demo/venv/lib/python3.8/site-packages/fedvision_deploy_toolkit/_deploy.py", line 44, in deploy
    _maybe_create_python_venv(machine)
  File "/home/yangyu/work/fed_demo/venv/lib/python3.8/site-packages/fedvision_deploy_toolkit/_deploy.py", line 69, in _maybe_create_python_venv
    raise RuntimeError(f"python executable {machine['python']} not valid")

**Comment by xinggang70** [comment]
问题是怎么解决的？能否加一个comment？谢谢！

**Comment by icey-zhang** [comment]
请问解决了嘛？我也有这个问题
