### ISSUE TITLE
GPU train

### ISSUE THREAD

**Issue by kevinsummer219** [FederatedAI/FedVision#20]
hi, 
   I have a question,  Can Fedvision surpport GPU train?  Can you share some GPU train step?

**Comment by sagewe** [comment]
> hi,
> I have a question, Can Fedvision surpport GPU train? Can you share some GPU train step?
not support well in next version, try handy install paddlepaddle-gpu  and modify device to gpu in [config](https://raw.githubusercontent.com/FederatedAI/FedVision/main/examples/paddle_detection/config.yaml)
